### ISSUE TITLE
404 error on download

### ISSUE THREAD

**Issue by pippinsplugins** [wpninjas/edd-git-download-updater#16]
I get a 404 error when trying to download a file fetched from Github: 
![screen shot 2015-09-01 at 4 15 15 pm](https://cloud.githubusercontent.com/assets/1034109/9616601/b50ca4a2-50c4-11e5-94fe-7094c0cfce1f.png)

**Comment by pippinsplugins** [comment]
Setting download method to `Redirect` fixed it.

Could that be taken care of automatically please?

**Comment by kstover** [comment]
Going to mark this as closed. I wasn't able to replicate it. We can offer the switch to "Redirect" as a simple fix if it comes up on a user's site.
