### ISSUE TITLE
Show admin notice is ZipArchive unavailable

### ISSUE THREAD

**Issue by mindctrl** [wpninjas/edd-git-download-updater#30]
Right now if ZipArchive is unavailable, the plugin returns early. [Reference](https://github.com/wpninjas/edd-git-download-updater/blob/v1.0.1/git-download-updater.php#L114-L115).

This has caused a little customer confusion. To troubleshoot the customer's server, I wrote a script to check for ZipArchive because I suspected he was missing it, and he was.

Can you show an admin notice instead of silently failing?

**Comment by cklosowski** [comment]
@mindctrl can you see if this works for you? To test the notice I had to switch the logic on the `class_exists` temporarily.

**Comment by cklosowski** [comment]
Merged closing.
