### ISSUE TITLE
rmdir on a non-empty folder

### ISSUE THREAD

**Issue by chriscct7** [wpninjas/edd-git-download-updater#4]
Keep getting this error everytime I try to save a GitHub repo:
Warning: rmdir(C:\Users\chris\Desktop\wamp\www\fes/wp-content/uploads/edd-git-tmp/): Directory not empty in {your code}

**Comment by chriscct7** [comment]
I actually can't test the plugin at all till this is fixed. Occurs when you go to make a new download, set it to a repo and hit save with WP_Debug on.

**Comment by kstover** [comment]
Hmm. I think I see the problem; C:\.... ;)

I'll dig into this as soon as I'm able and take care of it.

**Comment by kstover** [comment]
Hmm. I just created a download from scratch locally and it grabbed from GitHub properly and I didn't see the above error. Could there be a file-system error that I'm missing? Is the temporary git folder present? Is there anything in it on your machine?

**Comment by chriscct7** [comment]
It has to do with ones with folders. For example, try using EDD as your download item

**Comment by kstover** [comment]
Hmm. Did that. It grabbed the zip and worked as I'd expect. Not sure what's going on there. I've tested with EDD, Ninja Forms, and all of our extensions.

**Comment by chriscct7** [comment]
Weird. It could possibly be Windows I guess. I'm not sure.

**Comment by chriscct7** [comment]
I guess disregard this for now, and fix anything else and then push it back to ready for audit and we'll get someone with a different setup to test it to see if its an environmental thing

**Comment by kstover** [comment]
Is the slash causing problems? (C:\Users\chris\Desktop\wamp\www\fes/wp-content/uploads/edd-git-tmp/)

**Comment by kstover** [comment]
Well, I'd like to get it fixed; there's obviously something I've done wrong. :)

**Comment by chriscct7** [comment]
I'm not sure if its the slash. I don't think it is. Its downloaded the zip and put it in the right folder, so I don't really know.

**Comment by kstover** [comment]
I have a friend with a Windows machine; I'll get him to test it out and get to the bottom of it. :)

**Comment by kstover** [comment]
It has to be an issue with the filesystem. Maybe windows doesn't play well with scandir()?
