### ISSUE TITLE
Simplify logic

### ISSUE THREAD

**Issue by chriscct7** [wpninjas/edd-git-download-updater#6]
```if ( isset ( $file['git_url'] ) and ! empty( $file['git_url'] ) ) {```
can be 
```if (  ! empty( $file['git_url'] ) ) {```

empty by definition is ```!isset || $value == false```

so ```!empty is isset && $value != false```

**Comment by kstover** [comment]
Fixed. What happens when you write code really early in the morning and you're old like me. :)
