### ISSUE TITLE
Add Update button and stop using save_post

### ISSUE THREAD

**Issue by chriscct7** [wpninjas/edd-git-download-updater#8]
The operation you guys do on save_post seriously slows down the page load, as it takes alot of time to do. You should only run it on the first page save, and thereafter use ajax or a button that says update to update it.

**Comment by kstover** [comment]
This is something that I've been working on locally for a bit.

**Comment by kstover** [comment]
@chriscct7 Any recommendations from a UI perspective as to where this button fits in best?

**Comment by chriscct7** [comment]
Well if you move to autopulling, you can probably display: none; the file url field from EDD core
